### ISSUE TITLE
Please provide more documentation on SvgDataResolver

### ISSUE THREAD

**Issue by adrianknight89** [luberda-molinet/FFImageLoading#1138]
I'm a bit confused as to the use case for this class.

- Why do we need it to enable svgs on native?
- Why is the height parameter always 0 in the examples you provided?
- Why are you passing 64 for width in one sample even though svg width is 30?
- How should we allocate ImageView dimensions before loading the svg?

https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support

**Comment by daniel-luberda** [comment]
> Why do we need it to enable svgs on native?

It's because SVG support has a SkiaSharp dependency and it's included as a separate nuget package.

> Why is the height parameter always 0 in the examples you provided

FFImageLoading automatically maintains correct aspect, so if you set `width` - `height` will be auto-calculated, if you set `height` - `width` will be auto-calculated.

> Why are you passing 64 for width in one sample even though svg width is 30?

SVG is scalable, so widths / heights would be scaled to 64

> How should we allocate ImageView dimensions before loading the svg?

Could you elaborate?

BTW: Feel free to update WIKI - it's editable. Cheers :)
