### ISSUE TITLE
SVG plugin throwing Timeout exceeded getting exception details

### ISSUE THREAD

**Issue by trepik** [luberda-molinet/FFImageLoading#1193]
### Description

Can't make this svg plugin work for simple use case. Throwing the timeout exception.
When I comment out the ffSvg element in XAML no exception is thrown.

### Steps to Reproduce
This is the ffsvg code I'm using, the image file sits in resources directory in main project.

```
<ContentPage
...
xmlns:ffSvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms">
...
<StackLayout>
<ffSvg:SvgCachedImage Source="resource://MyApp.Resources.logo.svg"
                Margin="5,0"
                HeightRequest="40"
                VerticalOptions="End"/>
</StackLayout>
```
### Expected Behavior

working like a charm

### Actual Behavior

exception thrown no visual loaded

### Basic Information

- Version with issue: 2.4.3.840 and 2.4.4.859
- Last known good version: ???
- Platform: Xamarin.Forms 3.5.0.129452

**Comment by irongut** [comment]
I'm also having some issues using v2.4.3.840 with Xamarin.Forms v3.5.0.129452. 

I get an exception when I call: `CachedImageRenderer.Init(true);`

`System.TypeLoadException: VTable setup of type FFImageLoading.Forms.Platform.CachedImageFastRenderer failed occurred`

This does not occur when I use v2.4.5.860-pre. (I haven't tried v2.4.4.859 because of #1157)

@trepik You might want to try the prerelease package v2.4.5.860-pre or downgrade Xamarin.Forms to v3.4 which does work with v2.4.3.840 of FFImageLoading.

**Comment by trepik** [comment]
upgrading to v2.4.5.860-pre did not help, still the same issue

**Comment by trepik** [comment]
The issue was fixed by including the following line in the MainActivity.cs in Android project.
`FFImageLoading.Forms.Platform.CachedImageRenderer.Init(enableFastRenderer: true);`
