### ISSUE TITLE
When I try to display a gallery of 60+ images, they are downloaded sequentially which is very slowly

### ISSUE THREAD

**Issue by Korayem** [luberda-molinet/FFImageLoading#168]
It's dead slow in comparison to using normal Xamarin Forms Image, which apparently sends around 5 requests simultaneously.

**Comment by Korayem** [comment]
Update: I realized that's because FFImageLoading was using native .NET httpClient and not ModernHttpClient which was doing the high performance loading.

I simply ran the following in `public partial class App : Application`
```
//Set default image loading properties
//Reference: https://github.com/molinch/FFImageLoading/wiki/Advanced-Usage
ImageService.Initialize (new FFImageLoading.Config.Configuration () {
		HttpClient = new HttpClient (new NativeMessageHandler ())
});

```

**Comment by daniel-luberda** [comment]
I'll investigate it. Come back to you soon.

**Comment by molinch** [comment]
@Korayem XF sends 5 requests separately? Are you sure of that? Even though I don't think that sending concurrent requests will help on mobile devices: if you have a slow connection it will make things worse, if you have a good connection it will help...

> I thought it might be because FFImageLoading was using native .NET httpClient and not ModernHttpClient which was doing the high performance loading.
We don't use it because we encountered a few bugs with ModernHttpClient.
You can see: https://github.com/paulcbetts/ModernHttpClient/issues/184 and https://github.com/paulcbetts/ModernHttpClient/issues/185

These issues don't happen with default Mono's HttpClientHandler

**Comment by Korayem** [comment]
I will record a video and share difference in loading bulk images for later
investigation

**Comment by molinch** [comment]
@Korayem Scheduler changes are available in the latest 2.1 alpha 2 nuget package.
Could you give it a try and tell us if you still face this issue?
If it is still the case could you upload your screencast?

**Comment by molinch** [comment]
2.1 is now fully released

**Comment by molinch** [comment]
Please note that 2.2 will be around performances, not features.
We have tons of ideas to improve things.

Feel free to reopen if you still experience issues.
