### ISSUE TITLE
LoadingError should contain more information on what the error actually was

### ISSUE THREAD

**Issue by ravensorb** [luberda-molinet/FFImageLoading#175]
Right now the LoadingError event on CachedImage contains a hard coded string.  Ideally it would contain a little more information to help identify the problem -- maybe an error code as well (ex: 401, 404, 500, etc)?

**Comment by daniel-luberda** [comment]
@ravensorb  There are few cases when generic error is returned. I'll try to fix them all to get more details about it.

**Comment by molinch** [comment]
This cannot ship into 2.1 since there is too much code change involved for a minor functionality.
We will do it for 2.2

In order to do this we should get rid of `GenerateResult` enum in our iOS, Android & WP ImageLoaderTask.
Instead we should return the `LoadingResult` enum and add a couple of entries in it for each kind of error.

The TaskParameter `Error` callback would be changed to be:
```c#
public TaskParameter Error(Action<Exception, LoadingResult> action)
```

Some logic would have to be changed to rely correctly on the LoadingResult enum, since it contains more entries, maybe having some utilities extension methods like `IsSuccess` and `IsFailed`.

**Comment by daniel-luberda** [comment]
@ravensorb  `2.1.9-pre-168-core-r` has it redesigned, it catches and logs all exceptions. Please reopen it if doesn't work for you.
