### ISSUE TITLE
Support for bad/no connectivity? 

### ISSUE THREAD

**Issue by owlstack** [luberda-molinet/FFImageLoading#189]
Does this library have support to cache and load images from the background when the user has bad connection or loses connection so that the images are still loaded from the cache instead of showing a blank image (currently happening with the library). Where should I look for support on this functionality? 

Thank you! 

This is particularly for Xamarin.Forms

**Comment by michaeldimoudis** [comment]
I echo this statement. If there is no internet connection, you can see in the stack trace that a network call is been made to fetch the image, and that it obviously fails. App doesn't crash, but it would be great if this library can detect if the phone is connected to the net, and immediately return the cached image or placeholder image, instead of trying an internet connection which will obviously failed. I'm not sure if it's possible, but I might try Xam.Plugin.Connectivity in the FFImageLoading initialization method when I override HttpClient...

**Comment by owlstack** [comment]
@michaeldimoudis Please let me know if you got a solution either with returning the cached image or the placeholder image. How are you currently setting the placeholder image for FFImageLoading?

Thanks!

**Comment by molinch** [comment]
Makes sense it should not be difficult to add that functionality.

**Comment by daniel-luberda** [comment]
+1 Code needed for checking network on each platform is here: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Connectivity/Connectivity

**Comment by owlstack** [comment]
Currently, I'm using CachedImages and I'm setting the ErrorPlaceholder, so that when there's no internet, the placeholder images are shown but what if I want to cache my images that need internet to load. I want to cache it when the user first logins with internet connectivity but when they're offline, they can still see their cached images. I'm looking for a Xamarin.Forms solution using this library. 

I can't find a Forms implementation by James Montemagno. Should I just use the native Android solution provided?

**Comment by molinch** [comment]
Images that are loaded with the lib are automatically cached, hence available when offline. This is by default.

If you want to "preload" images this is also possible with the new `Preload` method.

**Comment by michaeldimoudis** [comment]
Hi I am having a pretty big issue now, I didn't want to create a new issue. With the latest RC 2.1.0-rc1, my images are NOT getting cached anymore. On each load it downloads the images again, and if I cut my network the error placeholder image appears. My app logic hasn't changed, just updated Xamarin Forms and FFImageLoading etc... is this a known issue? Has anything major changed here? I have just tested this in the iOS emulator so far...

**Comment by molinch** [comment]
@michaeldimoudis this issue is now fixed in git, should be fixed soon in nugets

**Comment by owlstack** [comment]
@molinch how do I set them available for offline use? If I don't set a placeholder for error and loading, then would they load even though there's low or no connection?

**Comment by molinch** [comment]
@owlstack What is implemented currently:
- loading images when there is network, these images are cached, hence they will be available offline and online
- if an image request is done while offline, and the image was not already cached, then the error placeholder will be displayed
- in both cases while the image loads the loading placeholder is displayed

What is not yet implemented:
- immediately checking network status instead of trying to start the request & see if it fails

**Comment by owlstack** [comment]
@molinch yes I had meant I wanted to preload the images using Xamarin.Forms. Is there an example on how to use the preload method? Thanks!

**Comment by martb1n** [comment]
Hi. Sorry,  don't want create new issue, but my problem related to this.
I try to explain behavior: I had very, very slow connection (near 0.03Mbit) but I had. I have list view with 30 items and each contains CachedImage with source as url. And also I have CachedImage with .png source, but this png don't display until I get good connection and load all images from url.
I use XF 2.1.0.6529 and FFImageLoading 2.0.7.1. I saw this behavior on iOS app

**Comment by molinch** [comment]
@martb1n I know it's annoying but that is the expected behaviour in 2.1.
This is something we want to improve for 2.2

**Comment by daniel-luberda** [comment]
Should be fixed in `2.1.9-pre-168-core-r`. Please reopen it if doesn't work for you.
