### ISSUE TITLE
No brightness transformation possible?

### ISSUE THREAD

**Issue by skubo** [luberda-molinet/FFImageLoading#247]
Somewhere in the project I found the reference to how color matrices are used in the ColorSpaceTransformation here: [https://docs.rainmeter.net/tips/colormatrix-guide/](https://docs.rainmeter.net/tips/colormatrix-guide/)

However if I try to create my own float matrix like this 
`new ColorSpaceTransformation( new float[][] {
            new float[] {1,0,0,0,0},
            new float[] {0,1,0,0,0},
            new float[] {0,0,1,0,0},
            new float[] {0,0,0,1,0},
            new float[] {b,b,b,0,1}
            )`
like suggested on that page, with b as a changing value for white factor of the color matrix, it does not change the brightness of the image at all. Looking into the code, I found that e.g. in `FFImageLoading.Transformations.Windows\ColorSpaceTransformation.cs` it's in fact not using the fifth row as "white" row like specified on that page, but as some sort of RGBA offset, which I don't quite yet understand how that works. 

Is it possible to implement a brightness transformation with the given filters, or does that need to be implemented in a custom filter?

**Comment by skubo** [comment]
Should add that the brightness matrix above does not work on any platform.

**Comment by molinch** [comment]
Thanks for debugging this.
@skubo Could you propose a PR for it?

**Comment by skubo** [comment]
sorry, I don't quite understand how color matrix transformations work at all, I was just try-and-erroring the example from that page mentioned

**Comment by molinch** [comment]
Any idea @daniel-luberda ?

**Comment by ckrempp91** [comment]
@skubo from my understanding the brightness of an image is impacted by the fourth row because that signifies the alpha channel for that specific color (based upon column). For example if you place positive numbers in fourth row like so [ R, G, B, A, 0f ]:

`new [] { 1f, 1f, 1f, 1f, 0f }`

Then you are specifying that you want the red, green, and blue colors present thus causing the image to be display more color and add white. The opposite is true when you set negative numbers in the fourth row like so [ R, G, B, A, 0f ]:

`new [] { -1f, -1f, -1f, -1f, 0f }`

Then you are specifying that you want the red, green, and blue colors to not be present thus causing the image to display less color and add black.

Here is a link to the definition of ColorMatrix that I was looking at: https://developer.android.com/reference/android/graphics/ColorMatrix.html

**Comment by skubo** [comment]
@ckrempp91 you're right this will change brightness. I'll close this ticket then. However, I still don't know what's the fifth row for. Does not seem to do anything?

**Comment by ckrempp91** [comment]
@skubo I am not entirely sure either, but I did find an article from windows that does explain how they utilize the fifth row in color matrix here https://msdn.microsoft.com/en-us/library/system.drawing.imaging.colormatrix(v=vs.110).aspx#Anchor_5

**Comment by daniel-luberda** [comment]
@ckrempp91 @skubo Yes, the explanation is correct. It's used for matrix values multiplication.
