### ISSUE TITLE
Should we include Transformations in a `Xamarin.FFImageLoading` nuget package?

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#433]
Should we include Transformations in a `Xamarin.FFImageLoading` nuget package and depreciate `Xamarin.FFImageLoading.Transformations`? Those dlls are quite small actually (~20KB dll for each platform) 

VOTE: https://goo.gl/cBYbjE

**Comment by hardcodet** [comment]
Not sure whether it's beyond the scope of thisrefactoring, but it looks like you had great code for general image processing here (e.g. scaling, rotating, getting image information etc.). Exposing that functionality for generic use during a refactoring would be awesome.

One of many scenarios: Rather than just downscaling a profile picture in the control, using your library code to actually scale it down before storing it on the backend.

**Comment by daniel-luberda** [comment]
@hardcodet Actually, it is now supported (latest prerelease). You can now do something like this: 

```C#
var output = await ImageService.Instance
   .LoadCompiledResource("image.png")
   .Transform(new SomeTransformation())
   .AsPNGStreamAsync();
```

**Comment by softwaremills** [comment]
I would be fine with including Transformations in the base package. What I wish was that iOS WebP support was a separate package, since that's a 1.2MB dependency I don't use.

**Comment by daniel-luberda** [comment]
@softwaremills I made another issue for your WebP package request: https://github.com/luberda-molinet/FFImageLoading/issues/710

**Comment by softwaremills** [comment]
Thanks a bunch, Daniel! I appreciate it!

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/859
