### ISSUE TITLE
Transformations aspect ratio (CropHeightRatio, CropWidthRatio parameters)

### ISSUE THREAD

**Issue by veryhumble** [luberda-molinet/FFImageLoading#448]
Hi,

I am using the Version `2.2.7-pre-294`.

While trying out RoundedTransformation i noticed that it will only make rounded corners if i remove `Aspect="AspectFill"`

This is the markup:
```
...
<RowDefinition Height="170" />
...
    <forms:CachedImage Grid.Row="0"
                         LoadingPlaceholder="image_loading"
                         Aspect="AspectFill"
                         Source="{Binding ThumbnailImageUrl}" >
        <forms:CachedImage.Transformations>
          <transformations:RoundedTransformation Radius="20" />
        </forms:CachedImage.Transformations>
      </forms:CachedImage>
```

Removing the `Aspect` property will apply the transformation just fine, but not stretching the image across the available space. So I tried `Fill` which works with transformations but does not preserve the aspect ratio, which is kind of important.

Am I doing something wrong here?

**Comment by daniel-luberda** [comment]
The order of operation is: 

- Transformations ((all transformations are done on original image)
- Aspect options

That's why you should know your image aspect ratio before transformations. By default those transformation will generate square image, if you want to modify that you should set `CropWidthRatio` / `CropHeightRatio` transformation parameters. Eg. `CropWidthRatio=2` and `CropHeightRatio=1` will generate 2:1 aspect ratio image.
