### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by NVentimiglia** [luberda-molinet/FFImageLoading#511]
Getting the following error when using the FFImage in a recycling list. To replicate I repeatedly hide and show my list (assumably recycling the cells and the images). The list works fine with regular images or when removing the FFImage. looks like it is there is a disposal exception from within the control ?

Android only. IOS has a possibly related issue where images never show.

```
 protected override void OnBindingContextChanged()
        {
            var model = BindingContext as AvatarVM;

            try
            {
                if (model != null)
                {
                    if (model.IsUser)
                        LargeImage2.Source = model.Picture;
                    else
                        LargeImage.Source = model.Picture;

                    if (model.HasSmallPicture)
                        SmallImage.Source = model.SmallPicture;
                }
            }
            catch (System.Exception ex)
            {
                LogController.LogError("Avatar", ex);
            }

            base.OnBindingContextChanged();
        }
```

```
02-28 21:22:46.327 W/Xamarin.Insights(31292): Warning: Unhandled exception: System.ObjectDisposedException: Cannot access a disposed object.
02-28 21:22:46.327 W/Xamarin.Insights(31292): Object name: 'Syncfusion.ListView.XForms.Android.ExtendedScrollViewRenderer'.
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00030] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:153 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00002] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:57 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at Android.Views.View.get_IsLayoutRequested () [0x00000] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.View.cs:6545 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at Xamarin.Forms.Platform.Android.ScrollViewRenderer+<OnScrollToRequested>d__43.MoveNext () [0x000ce] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:234 
02-28 21:22:46.327 W/Xamarin.Insights(31292): --- End of stack trace from previous location where exception was thrown ---
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/4009/9578cdcd/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:35 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4009/9578cdcd/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:81 
02-28 21:22:46.327 W/Xamarin.Insights(31292):   at (wrapper dynamic-method) System.Object:aff407e5-76e6-4284-b859-80829d4f8dfd (intptr,intptr)
```

**Comment by NVentimiglia** [comment]
closing, dont think this is FFImage

**Comment by SamVanCutsem** [comment]
I'm having the same issue. Any idea on how to solve it?

**Comment by daniel-luberda** [comment]
Yes, the exception from attached stack trace is definitely not caused by FFImageLoading. Cheers.

**Comment by balaameex** [comment]
I am having the same issue, Anybody found any solution

**Comment by balaameex** [comment]
Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Syncfusion.ListView.XForms.Android.ExtendedScrollViewRenderer'.
Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)<c8be8e08a22440d1a25fdbeea9ac909f>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<c8be8e08a22440d1a25fdbeea9ac909f>:0
Android.Views.View.get_IsLayoutRequested()<c73fb12392e14cd989a52e3b0f90cc63>:0
Xamarin.Forms.Platform.Android.ScrollViewRenderer.<OnScrollToRequested>d__58.MoveNext()<173f39d71f0d4d928f5bbea42e96ffa8>:0
Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()<c73fb12392e14cd989a52e3b0f90cc63>:0
Java.Lang.Thread.RunnableImplementor.Run()<c73fb12392e14cd989a52e3b0f90cc63>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<c73fb12392e14cd989a52e3b0f90cc63>:0
at (wrapper dynamic-method) System.Object.f9cd6b2e-4a9b-44d1-8905-0a45c2d6b5af(intptr,intptr)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.os.Handler.handleCallback()Handler.java:790
android.os.Handler.dispatchMessage()Handler.java:99
android.os.Looper.loop()Looper.java:164
android.app.ActivityThread.main()ActivityThread.java:6494
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run()RuntimeInit.java:438
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:807
