### ISSUE TITLE
UWP Stretch None

### ISSUE THREAD

**Issue by YZahringer** [luberda-molinet/FFImageLoading#544]
It is currently not possible to put an image without stretch in UWP.

If I do not set Expand on VericalOptions and HorizontalOptions, it shoud set the image to Stretch=None.

**Comment by EGoverde** [comment]
This is similar to issue #501. Wether the default should be set to stretch or not, at least the properties of the inner image object should be changeable on UWP. The pull request #502 would solve this, but perhaps there are better solutions. Sadly because the UWP class is internal there doesn't seem to be a workaround that doesn't involve editing the source.

**Comment by daniel-luberda** [comment]
#502 was merged, so I'll close this one. Thanks @EGoverde
