### ISSUE TITLE
Remember image loading error placeholder and skip retries after that. 

### ISSUE THREAD

**Issue by jorgenstorlie** [luberda-molinet/FFImageLoading#582]
I load images like this:

	var imageURL = AppDelegate.Getservice().GetImageUserIdURL(ObjectId, ObjectType);
taskImage = ImageService.Instance.LoadUrl(imageURL)
 .CacheKey(ObjectId.ToString())
.ErrorPlaceholder(localFilename, ImageSource.Filepath)
.LoadingPlaceholder(localFilename, ImageSource.Filepath);

this works, but I have a problem with Caching of errors.

I some cases the ObjectId does not have a image and then I want to the ErrorPlaceholder image.
That works, but this is not Cached.
Rows in the list that contains objects without images tries to get images all the time. It should Cache the information that it does not have any images.

Do I miss something?

**Comment by jorgenstorlie** [comment]
Anyone that have a solution on this?

**Comment by daniel-luberda** [comment]
Hi @jorgenstorlie,

Error images are definitely cached. It's something entirely different here - FFImageLoading tries to download that url every time `ImageService.Instance.LoadUrl` code is executed. What's more, it retries 3 times by default if it fails. You can configure that behavior (`RetryCount`/`RetryDelay`).

If you want to remember that the image loading failed, you should implement it by yourself (use some `bool` property for that and just skip image loading if it was previously set). You can use `OnError` callback for that - it should be easy.

**Comment by beylkhanovdamir** [comment]
@daniel-luberda 

Hi Daniel, I'm not sure that understand you, but how OnError callback can help me with caching error image. I think it must be immediately loaded from cache without time on any extra logic and checking

**Comment by SDV-MINI-DEV-2** [comment]
@daniel-luberda 

Hi Daniel, 
I've here the same problem.
Inside of a mvxrecyclerview I've some images that haven't a valid url (and I place in there an error placeholder).
When I scroll, the error placeholder is loaded again (with the fade animation).
So I've create a custom MvxCachedImageView class and I override the OnError event.
Inside of this class I've set a private bool variable (ex. _errorFound) that I set on true inside the OnError event. 
The problem is obviously that the recyclerview recycles the elements and this private variable is set to true also for other elements that do not have an error.

I think that a brief example you created could help considering that this is actually a common problem.

This is my code, in case it can serve

```
public class MvxImageViewNoRetry : MvxCachedImageView
    {
        private bool _error;

        public MvxImageViewNoRetry(Context context) : base(context) {

        }

        public MvxImageViewNoRetry(Context context, IAttributeSet attrs) : base(context, attrs) {
            OnError += MvxImageViewNoRetry_OnError;
        }

        public MvxImageViewNoRetry(IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer)
        {

        }

        private void MvxImageViewNoRetry_OnError(object sender, FFImageLoading.Args.ErrorEventArgs e)
        {
            _error = true;
        }

        protected override void OnPropertyChanged(string propertyName)
        {
            if (_error)
            {
                return;
            }
            else
            {
                base.OnPropertyChanged(propertyName);
            }
        }
    }
```
