### ISSUE TITLE
How does DownsampleToViewSize  work?

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#642]
I cant find detailed information about what are the pros and cons of DownsampleToViewSize ? 

1 ) Does it cache the internet image as defined width and height? so I use same image on 1 page 48x48 and other page 64x64, I will have total 2 cached image? This is expected to increase cache size on the other hand, it should increase image load time because of it is pre-rendred. Is it Correct?
2) if my assumption in 1st is correct, I guess this doesnt make sense to use in UWP desktop application as user may resize the application? It should be similar problem changing between portrait and landscape modes.  It causes pixels to be lost I believe.

What exact benefits do I get using DownsampleToViewSize ?

**Comment by daniel-luberda** [comment]
Hi @EmilAlipiev, 

Some explanation is on our WIKI page: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#downsampletoviewsize-bool-default-false

Feel free to update it (everyone can do it). 

> What exact benefits do I get using DownsampleToViewSize ?

>If set to true image will resize to an image view size. Please note: this could not work on some layouts (eg. absolute layouts without RequestWidth/RequestWidthHeight specified, LayoutOptions.Fill in some specific scenarios, etc). Algorithm for choosing size: First View.Width/View.Height is checked, if it’s ⇐ 0 it falls back to: View.RequestWidth/View.RequestHeight, if it’s ⇐ 0 it falls back to using DownsampleWidth/DownsampleHeight properties. It’s not the best option for image views that have no initial size defined. For that you should use DownsampleWidth or DownsampleHeight properties and set your downsample size manually.

> Does it cache the internet image as defined width and height? so I use same image on 1 page 48x48 and other page 64x64, I will have total 2 cached image? This is expected to increase cache size on the other hand, it should increase image load time because of it is pre-rendred. Is it Correct?

Yes, you will have two cached images (in memory cache) as we add downsampling size to the cache keys. That's why you have access to both approaches. If you use the same downsampling sizes on both images, you would use/cache only one image version. 

> 2) if my assumption in 1st is correct, I guess this doesnt make sense to use in UWP desktop application as user may resize the application? It should be similar problem changing between portrait and landscape modes. It causes pixels to be lost I believe.

Resizing windows is not used as often and memory cache is recycled all the time, so no harm here. It's still useful in cases like listviews, when you have the same image appearing many times.
