### ISSUE TITLE
iOS: CircleTransformation not found in xmlns clr-namespace

### ISSUE THREAD

**Issue by jsauvexamarin** [luberda-molinet/FFImageLoading#665]
I'm using FFImageLoading 2.2.9, and I'm seeing this error at runtime in iOS:

```
Position 46:15. Type fftransformations:CircleTransformation not found in xmlns clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations
```
Android works just fine.

The code is publicly viewable here:
https://github.com/xamarinhq/app-acquaint/blob/master/App/Acquaint.XForms/Acquaint.XForms/Pages/AcquaintanceListPage.xaml

When I comment out these lines, the iOS app executes without errors, but I no longer have circle images.
https://github.com/xamarinhq/app-acquaint/blob/master/App/Acquaint.XForms/Acquaint.XForms/Pages/AcquaintanceListPage.xaml#L38-L40

It's as if the CircleTransformation type doesn't exist in the iOS version of the FFImageLoading libs. `CachedImageRenderer.Init();` is being called on both platforms.

**Comment by daniel-luberda** [comment]
Hi @jsauvexamarin,

Just put this somewhere in you platform specific project **and** also PCL project: 

`var ignore = new CircleTransformation()`

or use the newsest prerelease (there were some additional changes which should prevent removing transformations because of Xamarin's linking feature - `Preserve` attribute)

**Comment by daniel-luberda** [comment]
Could you test the newest prerelease? (2.2.10.428) It should be fixed now. Please reopen if it's still a valid issue. Thanks
