### ISSUE TITLE
Crash on API 24+

### ISSUE THREAD

**Issue by sylvain-toptal** [luberda-molinet/FFImageLoading#756]
I don't have much to work with but consistently get this crash on APIs 24 and over.  I'm using version 2.2.20 but was also getting the issue on 2.2.10  This crash started appearing after I did a big refactoring to move to a Viewmodel pattern.  This entails that there are a lot more operations running in parallel whereas we used to load stuff linearly (and slowly...)

Thanks for any help.

```
10-09 11:24:10.989 E/mono-rt ( 1665): Stacktrace:
10-09 11:24:10.989 E/mono-rt ( 1665): 
10-09 11:24:10.989 E/mono-rt ( 1665):   at <unknown> <0xffffffff>
10-09 11:24:10.989 E/mono-rt ( 1665):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00012>
10-09 11:24:10.989 E/mono-rt ( 1665):   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00074] in <e499a5498b1b48379b88fe5ed629079f>:0
10-09 11:24:10.989 E/mono-rt ( 1665):   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0005f] in <e499a5498b1b48379b88fe5ed629079f>:0
10-09 11:24:10.989 E/mono-rt ( 1665):   at Android.Widget.ImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x00038] in <2e14bb2dd93a405e81838369ed72695b>:0
10-09 11:24:10.989 E/mono-rt ( 1665):   at FFImageLoading.Views.ManagedImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x00077] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Views\ManagedImageView.cs:165
10-09 11:24:10.989 E/mono-rt ( 1665):   at FFImageLoading.Targets.ImageViewTarget.Set (FFImageLoading.Work.IImageLoaderTask,FFImageLoading.Drawables.SelfDisposingBitmapDrawable,bool) [0x00020] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Targets\ImageViewTarget.cs:55
10-09 11:24:10.989 E/mono-rt ( 1665):   at FFImageLoading.PlatformImageLoaderTask`1/<>c__DisplayClass4_0<TImageView_REF>.<SetTargetAsync>b__0 () [0x0000b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:84
10-09 11:24:10.989 E/mono-rt ( 1665):   at FFImageLoading.Helpers.MainThreadDispatcher/<>c__DisplayClass5_0.<PostAsync>b__0 () [0x00008] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Helpers\MainThreadDispatcher.cs:44
10-09 11:24:10.989 E/mono-rt ( 1665):   at Java.Lang.Thread/RunnableImplementor.Run () [0x0000e] in <2e14bb2dd93a405e81838369ed72695b>:0
10-09 11:24:10.989 E/mono-rt ( 1665):   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00008] in <2e14bb2dd93a405e81838369ed72695b>:0
10-09 11:24:10.989 E/mono-rt ( 1665):   at (wrapper dynamic-method) object.8cfad20b-a362-4eda-8465-1706fdaaa79d (intptr,intptr) [0x00011] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
10-09 11:24:10.990 E/mono-rt ( 1665):   at (wrapper native-to-managed) object.8cfad20b-a362-4eda-8465-1706fdaaa79d (intptr,intptr) [0x00021] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
10-09 11:24:10.990 E/mono-rt ( 1665): /proc/self/maps:
10-09 11:24:10.990 E/mono-rt ( 1665): 12c00000-12e17000 rw-p 00000000 00:01 12296                              /dev/ashmem/dalvik-main space (deleted)
10-09 11:24:10.990 E/mono-rt ( 1665): 12e17000-1339e000 rw-p 00217000 00:01 12296                              /dev/ashmem/dalvik-main space (deleted)
10-09 11:24:10.990 E/mono-rt ( 1665): 1339e000-22c00000 ---p 0079e000 00:01 12296                              /dev/ashmem/dalvik-main space (deleted)
10-09 11:24:10.990 E/mono-rt ( 1665): 22c00000-22c01000 rw-p 00000000 00:01 12297                              /dev/ashmem/dalvik-main space 1 (deleted)
10-09 11:24:10.990 E/mono-rt ( 1665): 22c01000-32c00000 ---p 00001000 00:01 12297                              /dev/ashmem/dalvik-main space 1 (deleted)
10-09 11:24:10.990 E/mono-rt ( 1665): 582b7000-582bb000 r-xp 00000000 08:06 247                                /system/bin/app_process32
...

10-09 11:38:57.296 F/libc    ( 2002): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 2002 (istribution_dev)
```

**Comment by sylvain-toptal** [comment]
So I found a "work around" or maybe we were just not using FFIL properly.  All our calls were using the .Into() variant.  Switching them to .IntoAsync() fixes the crash

**Comment by daniel-luberda** [comment]
@sylvain-toptal Exception occurs at the line `base.SetImageDrawable(drawable);` - that's really unexpected. Maybe the rate of assigning new drawable is to high? When you use `IntoAsync` method, you actually wait for the image loading task to finish.

**Comment by sylvain-toptal** [comment]
It is indeed unexpected and it took me a while to find a working solution.  I hadn't noticed the .IntoAsync() version before.  It might be worth looking deeper into this since it occurs on APIs 24+ (possibly due to an underlying change on Google's APIs?)

**Comment by lukejaylarsen** [comment]
I'm getting this too on a RecyclerView with LoadCompiledResource... Pretty much exactly the same error log. My initial solution was to downgrade back to 2.2.0, but now I've found that it still happens, only rarely instead of every time. Below is the crash log from a user running 2.2.0: `10-10 18:15:47.047: E/mono-rt(10452): Stacktrace:
10-10 18:15:47.047: E/mono-rt(10452):   at <unknown> <0x
ffffffff>
10-10 18:15:47.047: E/mono-rt(10452):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00007>
10-10 18:15:47.047: E/mono-rt(10452):   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00073] in <ba092abe619c4ee5b5b74d0d2b7f994c>:0
10-10 18:15:47.047: E/mono-rt(10452):   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0005d] in <ba092abe619c4ee5b5b74d0d2b7f994c>:0
10-10 18:15:47.047: E/mono-rt(10452):   at Android.Widget.ImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x00031] in <8667555aa7244af09facf3213a4cb376>:0
10-10 18:15:47.047: E/mono-rt(10452):   at FFImageLoading.Views.ManagedImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x00013] in <7380c3e2060740bf9bb19144a37356dc>:0
10-10 18:15:47.047: E/mono-rt(10452):   at FFImageLoading.Targets.ImageViewTarget.Set (FFImageLoading.Work.IImageLoaderTask,FFImageLoading.Drawables.SelfDisposingBitmapDrawable,bool) [0x00020] in <7380c3e2060740bf9bb19144a37356dc>:0
10-10 18:15:47.047: E/mono-rt(10452):   at FFImageLoading.PlatformImageLoaderTask`1/<>c__DisplayClass6_0<TImageView_REF>.<SetTargetAsync>b__0 () [0x00016] in <7380c3e2060740bf9bb19144a37356dc>:0
10-10 18:15:47.047: E/mono-rt(10452):   at FFImageLoading.Helpers.MainThreadDispatcher/<>c__DisplayClass5_0.<PostAsync>b__0 () [0x00008] in <7380c3e2060740bf9bb19144a37356dc>:0
10-10 18:15:47.047: E/mono-rt(10452):   at Java.Lang.Thread/RunnableImplementor.Run () [0x00008] in <8667555aa7244af09facf3213a4cb376>:0
10-10 18:15:47.047: E/mono-rt(10452):   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00008] in <8667555aa7244af09facf3213a4cb376>:0
10-10 18:15:47.047: E/mono-rt(10452):   at (wrapper dynamic-method) object.63f2aa80-687e-4b15-b724-1e31ab5ee7b6 (intptr,intptr) <0x0001f>
10-10 18:15:47.047: E/mono-rt(10452):   at (wrapper native-to-managed) object.63f2aa80-687e-4b15-b724-1e31ab5ee7b6 (intptr,intptr) <0x000ab>`

**Comment by daniel-luberda** [comment]
Could yout try newest prerelease nuget? I added a lock that could prevent those kind of errors.

**Comment by daniel-luberda** [comment]
Please reopen if you still experience it in 2.2.21 stable.

**Comment by sylvain-toptal** [comment]
havent had time to try, sorry

**Comment by fedemkr** [comment]
I'm using v2.2.25 and it's still happenning. In my case, I have a `ViewPager` and in one of the pages I have a fragment with a `MvxGridView`. Each item has a `FFImageLoading.Views.ImageViewAsync`  that is loaded in an adapter using 
```csharp
var image = view.FindViewById<ImageViewAsync>(Resource.Id.attachment_image);

var work = ImageService.Instance.LoadUrl(item.ImagePath)
              .LoadingPlaceholder("@drawable/no_attachment", FFImageLoading.Work.ImageSource.CompiledResource)
              .ErrorPlaceholder("@drawable/no_attachment", FFImageLoading.Work.ImageSource.CompiledResource)
              .DownSample(100, 100)
              .Into(image);
```
The error occurs when images are loading at the first time (i.e. they are not catched yet) and I navigate from one of the pages to another view and then navigate back to the viewpager's view.

I've **workarounded** this by creating a class to hold and cancel all the IScheduledWork:
```csharp
public class ImageScheduledWorkHelper
{
    private List<IScheduledWork> imageScheduledWorks = new List<IScheduledWork>();

    private ImageScheduledWorkHelper()
    {
    }

    private static Lazy<ImageScheduledWorkHelper> _instance = new Lazy<ImageScheduledWorkHelper>(() => new ImageScheduledWorkHelper());
    public static ImageScheduledWorkHelper Instance => _instance.Value;

    public void Add(IScheduledWork work)
    {
        this.imageScheduledWorks.Add(work);
    }

    public void CancelAll()
    {
        foreach (var sw in this.imageScheduledWorks)
        {
            if (!sw.IsCompleted)
                sw.Cancel();
        }

        this.imageScheduledWorks.Clear();
    }
}
```
So after loading Into the image using the `ImageService.Instance.LoadUrl` I just add to the helper the IScheduledWork returned using `ImageScheduledWorkHelper.Instance.Add(work);` and then in the `OnPause` method of the `ViewPager`'s view I just call `ImageScheduledWorkHelper.Instance.CancelAll();` to prevent the scheduled works to continue loading the images.

Hope it helps someone in the meantime.
