### ISSUE TITLE
Advice / Help: ListView with a lot of images

### ISSUE THREAD

**Issue by stringo** [luberda-molinet/FFImageLoading#804]
Hi guys, I just send an email to: danlub01@gmail.com asking for some recommendations with two ListViews in my project. It is fine or you better prefer to have all the details here?

Thanks in advance.

**Comment by daniel-luberda** [comment]
Hi @stringo,

Some performance tips responding to you email. In ListView scenarios you should consider:

1. You want to set `LoadingDelay` property to some higher `Timespan` value (15ms default), it will give you a UI better overall experience when fast scrolling
2. You don't want to use bindings, as they're really slow. Please use this technique: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled
3. You want to set `DownsampleToViewSize` to `true`. When using `DownsampleToViewSize`, please be sure your view has a constant size defined, otherwise, it will fallback to some default low value (bad quality). It's described in the wiki, also you'll get some warning logs. 
4. On Android, you want to use the latest version, which uses fast renderer by default (if available). You can also force to enable it with: `CachedImageRenderer.Init(true);`

Best,
Daniel
