### ISSUE TITLE
CachedImage ignoring WidthRequest in FFImageLoading 2.3.1

### ISSUE THREAD

**Issue by AlexanderMelchers** [luberda-molinet/FFImageLoading#866]
Hi all,

Today I updated our project's FFImageLoading NuGet-packages (Xamarin.FFImageLoading, Xamarin.FFImageLoading.Forms and Xamarin.FFImageLoading.Transformations) from version 2.2.25 to **2.3.1**.

Since then, I've noticed that one of the images used in our App to provide users with a circular profile image - using a custom class derived from `CircleCachedImage`, yet which only sets a couple of default values for properties - no longer scales these profile images up to the width specified in the `WidthRequest`-attribute used in our XAML-layout. This behaviour was observed on both iOS and Android, though the specific way each platform expresses it differs. On Android, the image simply doesn't scale up - even when switching from the `AspectFit` to the `AspectFill` aspect ratio - but remains circular in shape; in other words, the circle seems to assume the image actual size. On iOS, on the other hand, the image no longer appears circular - thus, probably the circle mask knows what to do - but now appears square.

Our XAML-code looks like below:
```
<controls:ProfileImage
	x:Name="ProfileImage"
	Grid.Column="0"
	ErrorPlaceholder="{Binding DefaultProfileImageSource}"
	WidthRequest="{Binding ImageWidthRequest, Source={x:Reference Self}}"
	Aspect="AspectFit"
	VerticalOptions="Center"
	HorizontalOptions="Center" />
```

Where `Self` is a reference to the `ContentView`'s own XAML-definition. This then is set into a grid.

Fortunately, the problem seemed easy enough to resolve by reverting the Xamarin.FFImageLoading.Forms NuGet back to version 2.2.25.

Could you please look into this so that we continue updating our libraries in future releases of FFImageLoading? Unfortunately, I can't share any further code, but our Xamarin.Forms version is 2.5.0.121934, in case this may be relevant. On Android I am using fast renderers, but have tried setting their use to `false` without luck.

Thanks for your help!

Best regards,
Alexander.

**Comment by daniel-luberda** [comment]
**Please read 2.3.1 release docs**

**Comment by daniel-luberda** [comment]
# Xamarin.Forms - IMPORTANT
- FFImageLoading had a regression since 2.2.4 which caused `CachedImage` to always fill entire space available (different behaviour than `Image`). It's now fixed. You can get old behaviour with `CachedImage.FixedOnMeasureBehavior = false;` (static property)
- For older Xamarin.Forms version set `CachedImage.FixedAndroidMotionEventHandler = false` if experiencing any gesture recognizers problems on Android. (static property)
- On Android you have to specify if you want to enable / disable fast renderer `CachedImageRenderer.Init(enableFastRenderer: [true/false])`

**Comment by AlexanderMelchers** [comment]
Hi Daniel,

Thanks for the quick response! I must say I suspected something like that might have been the case - that is, that functionality had changed to conform to a Xamarin standard - I could not find the release notes (where are these to be found?), and all the documentation I was able to find did not mention anything along these lines. Also, such being the case, I would have expected setting the image to `AspectFill` to scale up to the requested size. And indeed, the underlying image does seem to do so, yet the circle mask does not.

In any case, your first suggestion resolved my issue. Thanks!

**Comment by daniel-luberda** [comment]
- All releases are here: https://github.com/luberda-molinet/FFImageLoading/releases
- You can have old behaviour with `CachedImage.FixedOnMeasureBehavior = false;` (call it somewhere on app startup)

> And indeed, the underlying image does seem to do so, yet the circle mask does not.

Probably your transformation is removed by linker. Put `var ignore = typeof(CircleTransformation)` somewhere in platform specific code. Also please make sure you're setting Transformations assign it as a new ListView, otherwise it won't recognise transformations changes.

**Comment by AlexanderMelchers** [comment]
Thanks for the info! I'll keep a better eye on the release notes next time ;)
